// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQee9pVbMlkLFqtb0dngLPfbdJSAFlBVY',
    appId: '1:960453175500:web:4ec16bf5d621cba6037a69',
    messagingSenderId: '960453175500',
    projectId: 'ecosphere-f3790',
    authDomain: 'ecosphere-f3790.firebaseapp.com',
    storageBucket: 'ecosphere-f3790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mmv0kIHDyiWsTD_DOjIbp1R7BpnVE7A',
    appId: '1:960453175500:android:770f2bd36a5d3621037a69',
    messagingSenderId: '960453175500',
    projectId: 'ecosphere-f3790',
    storageBucket: 'ecosphere-f3790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6TXgnfUJCYneCrBY_FvONhbQ-gIpGa14',
    appId: '1:960453175500:ios:c409421ddc27d74b037a69',
    messagingSenderId: '960453175500',
    projectId: 'ecosphere-f3790',
    storageBucket: 'ecosphere-f3790.appspot.com',
    iosClientId: '960453175500-a4k2p7mpu6ponrrjb64i8ehqr00gdgrt.apps.googleusercontent.com',
    iosBundleId: 'cpv.eco.sphere.app',
  );
}
